projects:
  villagekeep:
    schemaPath: src/graphql/schema.json
    includes:
      - graphql/**/*.js
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: javascript
        generatedFileName: ''
        docsFilePath: src/graphql
